site_author: Ness
site_name: Tonutils
site_url: https://tonutils.ness.su/
site_description: Documentation for tonutils — Python library for working with TON Blockchain, including examples, how-to guides, and reference materials.

repo_url: https://github.com/nessshon/tonutils/
edit_uri: https://github.com/nessshon/tonutils/tree/main/docs/

use_directory_urls: true

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/logo.png
  logo: assets/logo.png
  features:
    - announce.dismiss
    - content.code.copy
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.footer
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - autorefs
  - include-markdown
  - social:
  - minify:
      minify_html: true
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: ru
          name: Русский
          nav_translations:
            Overview: Обзор

            Guide: Руководство
            Installation and Initialization: Установка и Инициализация
            Getting Testnet Assets: Получение Тестовых Токенов
            Usage Scenarios: Сценарии Использования
            Usage Examples: Примеры Использования
            Using TON Connect: Использование TON Connect
            Wallet Operations: Операции с Кошельком
            Working with Jettons: Операции с Jetton
            Working with NFTs: Операции с NFT
            Managing TON DNS: Управление TON DNS

            Cookbooks: Рецепты
            TON Connect Integration: Интеграция TON Connect
            TON Connect Telegram Bot: Telegram-бот с TON Connect
            Creating Vanity Address: Создание Красивого Адреса
            Creating Compressed NFTs: Создание Сжатых NFT
            Minting TON Subdomains: Выпуск Поддоменов TON

            How To: Как
            Get Contract Information: Получить Информацию о Контракте
            Get Contract Code and Data: Получить Код и Данные Контракта
            Get NFT Item Address: Получить Адрес NFT-Элемента
            Get Jetton Wallet Address: Получить Адрес Кошелька Jetton
            Create Multiple Wallets: Создать Несколько Кошельков
            Send Encrypted Message: Отправить Зашифрованное Сообщение
            Send Gasless Transaction: Отправить Транзакцию Без Комиссии
            Send/Claim Mintless Jetton: Отправить/Получить Mintless-Jetton
            Use FunC Hash Functions: Использовать Хеш-Функции FunC

            Sponsors: Спонсоры
            Donate: Поддержать

nav:
  - Overview: index.md

  - Guide:
      - Installation and Initialization: guide/installation-and-initialization.md
      - Getting Testnet Assets: guide/getting-testnet-assets.md
      - Usage Scenarios: guide/usage-scenarios.md
      - Usage Examples:
          - Wallet Operations: guide/examples/wallet-operations.md
          - Working with Jettons: guide/examples/jetton-operations.md
          - Working with NFTs: guide/examples/nft-operations.md
          - Managing TON DNS: guide/examples/dns-operations.md
          - Using TON Connect: guide/examples/ton-connect-operations.md

  - Cookbooks:
      - TON Connect Integration: cookbook/tonconnect-integration.md
      - TON Connect Telegram Bot: cookbook/tonconnect-telegram.md
      - Creating Vanity Address: cookbook/vanity.md
      - Creating Compressed NFTs: cookbook/cnft.md
      - Minting TON Subdomains: cookbook/subdomains.md

  - How To:
      - Get Contract Information: how-to/get-contract-information.md
      - Get Contract Code and Data: how-to/get-contract-code-and-data.md
      - Get NFT Item Address: how-to/get-nft-item-address.md
      - Get Jetton Wallet Address: how-to/get-jetton-wallet-address.md
      - Create Multiple Wallets: how-to/create-multiple-wallets.md
      - Send Encrypted Message: how-to/send-encrypted-message.md
      - Send Gasless Transaction: how-to/send-gasless-transaction.md
      - Send/Claim Mintless Jetton: how-to/send-claim-mintless-jetton.md
      - Use FunC Hash Functions: how-to/use-func-hash-functions.md

  - Sponsors: sponsors.md
  - Donate: donate.md

extra:
  analytics:
    provider: google
    property: G-4SLDSR08T5
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/nessshon
    - icon: fontawesome/brands/github
      link: https://github.com/nessshon

extra_javascript:
  - assets/js/share.js

copyright: "Created with ❤️ by Ness"
